type IU = "Iue";
type Upper = Uppercase<IU>;
// type Upper = "IUE"
type Lower = Lowercase<IU>;
// type Lower = "iue"
type Capital = Capitalize<IU>;
// type Capital = "Iue" // 첫번째 글자 대문자
type UnCapital = Uncapitalize<IU>;
// type UnCapital = "iue" // 첫번째 글자 소문자